import os
import glob
import yaml
import argparse
import shutil
import logging
from typing import Dict, List, Tuple, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

# Constants
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "../config.yaml")

# Type alias for structure: {Category: [(Title, Filename), ...]}
StructureType = Dict[str, List[Tuple[str, str]]]

def load_config() -> Dict[str, Any]:
    """Load configuration from YAML file."""
    if not os.path.exists(CONFIG_PATH):
        return {}
    try:
        with open(CONFIG_PATH, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    except (yaml.YAMLError, IOError) as e:
        logging.error(f"Failed to load config: {e}")
        return {}

def get_category_from_file(filepath: str) -> str:
    """Reads the first line of the file to check for <!-- Category: X -->."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            first_line = f.readline()
            if first_line.startswith("<!-- Category:"):
                return first_line.split(":")[1].split("-->")[0].strip()
    except (IOError, OSError, UnicodeDecodeError) as e:
        logging.warning(f"Could not read category from {filepath}: {e}")
    return "Uncategorized"

def get_title_from_file(filepath: str) -> str:
    """Naive title extraction (filename or first header)."""
    filename = os.path.basename(filepath).replace(".md", "")
    # Try to find first # Header
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.readlines()
            for line in lines:
                if line.startswith("# "):
                    return line[2:].strip()
    except (IOError, OSError, UnicodeDecodeError) as e:
        logging.warning(f"Could not read title from {filepath}: {e}")
    return filename

def organize_for_github(wiki_dir: str, structure: StructureType, config: Dict[str, Any]) -> None:
    """Organize documentation for GitHub Wiki (flat structure with sidebar)."""
    project_name = config.get('project_name', 'Project')

    # Generate Home.md
    home_content = f"# {project_name} Documentation\n\n"
    home_content += "Auto-generated by AI Docs.\n\n"

    for cat in sorted(structure.keys()):
        home_content += f"## {cat}\n"
        for title, filename in structure[cat]:
            home_content += f"- [{title}]({filename})\n"
        home_content += "\n"

    with open(os.path.join(wiki_dir, "Home.md"), "w", encoding="utf-8") as f:
        f.write(home_content)

    # Generate _Sidebar.md
    sidebar_content = ""
    for cat in sorted(structure.keys()):
        sidebar_content += f"### {cat}\n"
        for title, filename in structure[cat]:
            sidebar_content += f"- [{title}]({filename})\n"
        sidebar_content += "\n"

    with open(os.path.join(wiki_dir, "_Sidebar.md"), "w", encoding="utf-8") as f:
        f.write(sidebar_content)

    logging.info(f"Created Home.md and _Sidebar.md with {sum(len(v) for v in structure.values())} entries")

def organize_for_azure_devops(wiki_dir: str, structure: StructureType, config: Dict[str, Any]) -> None:
    """Organize documentation for Azure DevOps Wiki (hierarchical with .order files)."""
    project_name = config.get('project_name', 'Project')
    root_order: List[str] = ["Home"]

    for cat in sorted(structure.keys()):
        # Sanitize category name for folder
        safe_cat = cat.replace(" ", "-").replace("/", "-")
        cat_dir = os.path.join(wiki_dir, safe_cat)

        if not os.path.exists(cat_dir):
            os.makedirs(cat_dir)

        root_order.append(safe_cat)
        cat_order: List[str] = []

        for title, filename in structure[cat]:
            # Move file to category subfolder
            src = os.path.join(wiki_dir, filename)
            dst = os.path.join(cat_dir, filename)

            # Only move if source exists
            if os.path.exists(src):
                shutil.move(src, dst)

            # Add to category .order
            fname_no_ext = filename.replace(".md", "")
            cat_order.append(fname_no_ext)

        # Write .order for the category
        with open(os.path.join(cat_dir, ".order"), "w", encoding="utf-8") as f:
            f.write("\n".join(cat_order))

    # Write root .order
    with open(os.path.join(wiki_dir, ".order"), "w", encoding="utf-8") as f:
        f.write("\n".join(root_order))

    # Generate Home.md (Index)
    home_content = f"# {project_name} Documentation\n\n"
    home_content += "Auto-generated by AI Docs.\n\n"

    for cat in sorted(structure.keys()):
        safe_cat = cat.replace(" ", "-").replace("/", "-")
        home_content += f"## {cat}\n"
        for title, filename in structure[cat]:
            home_content += f"- [{title}]({safe_cat}/{filename})\n"
        home_content += "\n"

    with open(os.path.join(wiki_dir, "Home.md"), "w", encoding="utf-8") as f:
        f.write(home_content)

    logging.info(f"Created {len(structure)} category folders with .order files")

def main() -> None:
    parser = argparse.ArgumentParser(description="Organize generated documentation for wiki platforms.")
    parser.add_argument(
        "--platform",
        default="github",
        choices=["github", "azure_devops"],
        help="Target platform (github or azure_devops)"
    )
    args = parser.parse_args()

    config = load_config()
    wiki_dir: str = config.get("wiki_dir", "wiki_content")

    if not os.path.exists(wiki_dir):
        logging.error(f"Directory {wiki_dir} does not exist.")
        return

    # Glob all md files in root of wiki_dir
    md_files: List[str] = glob.glob(os.path.join(wiki_dir, "*.md"))

    # Build structure: {Category: [(Title, Filename), ...]}
    structure: StructureType = {}

    # Reserved wiki files to skip
    reserved_files = {"Home.md", "_Sidebar.md", "_Footer.md", "_Header.md"}

    for md_file in md_files:
        filename = os.path.basename(md_file)
        if filename in reserved_files:
            continue

        category = get_category_from_file(md_file)
        title = get_title_from_file(md_file)

        if category not in structure:
            structure[category] = []
        structure[category].append((title, filename))

    # Sort entries within each category
    for cat in structure:
        structure[cat].sort()

    if not structure:
        logging.warning("No documentation files found to organize.")
        return

    if args.platform == "azure_devops":
        organize_for_azure_devops(wiki_dir, structure, config)
    else:
        organize_for_github(wiki_dir, structure, config)

    logging.info(f"Wiki organization complete for {args.platform}.")

if __name__ == "__main__":
    main()
