import os
import glob
import yaml

# Constants
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "../config.yaml")

def load_config():
    if not os.path.exists(CONFIG_PATH):
        return {{}}
    with open(CONFIG_PATH, "r") as f:
        return yaml.safe_load(f)

def get_category_from_file(filepath):
    """Reads the first line of the file to check for <!-- Category: X -->."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            first_line = f.readline()
            if first_line.startswith("<!-- Category:"):
                return first_line.split(":")[1].split("-->")[0].strip()
    except:
        pass
    return "Uncategorized"

def get_title_from_file(filepath):
    """Naive title extraction (filename or first header)."""
    filename = os.path.basename(filepath).replace(".md", "")
    # Try to find first # Header
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.readlines()
            for line in lines:
                if line.startswith("# "):
                    return line[2:].strip()
    except:
        pass
    return filename

def main():
    config = load_config()
    wiki_dir = config.get("wiki_dir", "wiki_content")
    
    if not os.path.exists(wiki_dir):
        print(f"Directory {wiki_dir} does not exist.")
        return

    md_files = glob.glob(os.path.join(wiki_dir, "*.md"))
    
    # Structure: {Category: [(Title, Filename)]}
    structure = {{}}
    
    for md_file in md_files:
        filename = os.path.basename(md_file)
        if filename in ["Home.md", "_Sidebar.md", "_Footer.md", "_Header.md"]:
            continue
            
        category = get_category_from_file(md_file)
        title = get_title_from_file(md_file)
        
        if category not in structure:
            structure[category] = []
        structure[category].append((title, filename))

    # Sort
    for cat in structure:
        structure[cat].sort()

    # Generate Home.md
    home_content = f"# {config.get('project_name', 'Project')} Documentation\n\n"
    home_content += "Auto-generated by AI Docs.\n\n"
    
    for cat in sorted(structure.keys()):
        home_content += f"## {cat}\n"
        for title, filename in structure[cat]:
            # Wiki link format: [Title](Filename) (GitHub Wiki usually handles this, or just relative links)
            home_content += f"- [{title}]({filename})\n"
        home_content += "\n"
        
    with open(os.path.join(wiki_dir, "Home.md"), "w", encoding="utf-8") as f:
        f.write(home_content)
        
    # Generate _Sidebar.md
    sidebar_content = ""
    for cat in sorted(structure.keys()):
        sidebar_content += f"### {cat}\n"
        for title, filename in structure[cat]:
            sidebar_content += f"- [{title}]({filename})\n"
        sidebar_content += "\n"
        
    with open(os.path.join(wiki_dir, "_Sidebar.md"), "w", encoding="utf-8") as f:
        f.write(sidebar_content)

    print("Wiki organization complete.")

if __name__ == "__main__":
    main()
